services: docker
language: bash

env:
  - VERSION=0.23.0
  - VERSION=0.25.1
  - VERSION=0.27.1
  - VERSION=0.30.2
  - VERSION=0.35.1

install:
    - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$DOCKER_USERNAME/le-certbot:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$image"

after_script:
  - docker images
