services: docker
language: bash

env:
  - VERSION=0.38.0

install:
    - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="$DOCKER_USERNAME/le-certbot:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$image"

after_script:
  - docker images
